---
title: "import gsheet"1
---

loguearse
```{r}
# Load the googlesheets4 package
library(googlesheets4)

# Set the Google user name
# options(googlesheets4.email = "dantonio@mzptec.com")

# Authenticate with Google Sheets (you may be prompted to sign in)
gs4_auth()

```

Cargar la tabla VL2-R-01-Registro de mediciones
```{r}
options(
  date.format = "%d/%m/%y",
  stringsAsFactors = FALSE)

# Get the sheet ID and sheet name
sheet_id <- "1k10kj7jHHr8vDWXKHHN4v6UCd2gn5u5cq2a9960cfTo"
sheet_name <- "01_Registro"

# Set the range to read, starting from the fourth row
range <- paste0(sheet_name, "!A4:AZ")

# Read the sheet data into R as a data frame, using the fourth row as the column names
my_data <- read_sheet(sheet_id, sheet_name, range, col_names = TRUE)
my_data$Fecha <- as.Date(my_data$Fecha)

# convert columns  to numeric
my_data$Pmed_base = as.numeric(as.character(my_data$Pmed_base))
my_data$Pmed_A10 = as.numeric(as.character(my_data$Pmed_A10))
my_data$`A10 (600s+CT) [Pa]` = as.numeric(as.character(my_data$`A10 (600s+CT) [Pa]`))
my_data$`A1 (60s+CT) [Pa]` = as.numeric(as.character(my_data$`A1 (60s+CT) [Pa]`))
my_data$`A5 (300s+CT) [Pa]` = as.numeric(as.character(my_data$`A5 (300s+CT) [Pa]`))
my_data$`A20 (1200s+CT) [Pa]` = as.numeric(as.character(my_data$`A20 (1200s+CT) [Pa]`))
my_data$`CT [seg]` = as.numeric(as.character(my_data$`CT [seg]`))
my_data$Alpha <- as.numeric(as.character(my_data$Alpha))
my_data$`Nro Cartucho` <- as.character(my_data$`Nro Cartucho`)
my_data$`MCF ??` = as.numeric(as.character(my_data$`MCF ??`))
my_data$`Presion de desprendimiento [Pa]` = as.numeric(as.character(my_data$`Presion de desprendimiento [Pa]`))
my_data$`CT [seg]` = as.numeric(as.character(my_data$`CT [seg]`))

# creamos nueva columna deltaPmed con el resultado de la diferencia entre dos columnas
my_data$deltaPmed <- my_data$Pmed_A10 - my_data$Pmed_base

```

subset de la tabla para eliminar mediciones que no deben ser consideradas, según el criterio del análisis
```{r}
#------ subset de la tabla para eliminar mediciones que no deben ser consideradas, según el criterio del análisis

#eliminamos las observaciones que NO se deben considerar en el análisis
subset_data <- subset(my_data, `Problema`=="ninguno")

#eliminamos mediciones sin datos de A10
subset_data <- subset_data[!is.na(subset_data$`A10 (600s+CT) [Pa]`), ]


# Discard NA's in subset_data$`Comportamiento curva Pmed`
#my_data <- my_data[!is.na(my_data$`Comportamiento curva Pmed`), ]

# Discard NA's in subset_data$`Comportamiento curva Pmed`
#my_data <- subset(my_data, `Comportamiento curva Pmed`!="NA")

# Discard cisnes in subset_data$`Comportamiento curva Pmed`
#my_data <- subset(my_data, `Comportamiento curva Pmed`!="cisne")
```

