---
title: "Plot curvas un dataset"
output: html_notebook
---

```{r}
# import measurement table

# load data in 'global' chunk so it can be shared
# by all users of the dashboard

# Load the googlesheets4 package
library(googlesheets4)

# Authenticate with Google Sheets (you may be prompted to sign in)
gs4_auth(email=TRUE)

options(date.format = "%d/%m/%y", stringsAsFactors = FALSE)

# Cargar la tabla VL2-R-01-Registro de mediciones
# Get the sheet ID and sheet name
sheet_id <- "1k10kj7jHHr8vDWXKHHN4v6UCd2gn5u5cq2a9960cfTo"
sheet_name <- "01_Registro"
# Set the range to read, starting from the fourth row
range <- paste0(sheet_name, "!A4:AI")
# Read the sheet data into R as a data frame, using the fourth row as the column names
my_data <- read_sheet(sheet_id, sheet_name, range, col_names = TRUE)
# convert columns  to numeric
my_data$Fecha <- as.Date(my_data$Fecha)
my_data$Pmed_base = as.numeric(as.character(my_data$Pmed_base))
my_data$Pmed_A10 = as.numeric(as.character(my_data$Pmed_A10))
my_data$`A10 (600s+CT) [Pa]` = as.numeric(as.character(my_data$`A10 (600s+CT) [Pa]`))
my_data$`A10R` = 100/(1+1400/my_data$`A10 (600s+CT) [Pa]`)
my_data$`A1 (60s+CT) [Pa]` = as.numeric(as.character(my_data$`A1 (60s+CT) [Pa]`))
my_data$`A5 (300s+CT) [Pa]` = as.numeric(as.character(my_data$`A5 (300s+CT) [Pa]`))
my_data$`A20 (1200s+CT) [Pa]` = as.numeric(as.character(my_data$`A20 (1200s+CT) [Pa]`))
my_data$`CT [seg]` = as.numeric(as.character(my_data$`CT [seg]`))
my_data$Alpha <- as.numeric(as.character(my_data$Alpha))
my_data$`Nro Cartucho` <- as.character(my_data$`Nro Cartucho`)
my_data$`MCF ??` = as.numeric(as.character(my_data$`MCF ??`))
my_data$`Presion de desprendimiento [Pa]` = as.numeric(as.character(my_data$`Presion de desprendimiento [Pa]`))
my_data$`CT [seg]` = as.numeric(as.character(my_data$`CT [seg]`))
my_data$Frecuencia_Hz = as.numeric(as.character(my_data$Frecuencia_Hz))
my_data$`Canal abierto Promedio QC2 [Pa]` = as.numeric(as.character(my_data$`Canal abierto Promedio QC2 [Pa]`))
my_data$Medicion <- paste(my_data$Prueba,my_data$Medicion) 
my_data$`Canal cerrado Promedio QC1 [Pa]` = as.numeric(as.character(my_data$`Canal cerrado Promedio QC1 [Pa]`))
# Create new column deltaPmed 
my_data$deltaPmed <- my_data$Pmed_A10 - my_data$Pmed_base
#eliminamos las observaciones que NO se deben considerar en el análisis y sin datos en A10
subset_data <- subset(my_data, `Problema`=="ninguno")
subset_data <- subset_data[!is.na(subset_data$`A10 (600s+CT) [Pa]`), ]


# parse data files

# set the directory path
dir_path <- "/home/dario/Documents/mediciones_vilas02/data"

file_extension <- ".dat"

# Find all files with the specified extension recursively in the directory
all_files <- list.files(path = dir_path, recursive = TRUE, pattern = file_extension, full.names = TRUE)

#file_list_nopath <- basename(file_list)


# Append ".dat" to file_name column
subset_data$MedicionArchivo <- paste(subset_data$Medicion, ".dat", sep = "")


# Filter files to be loaded based on file_names_list
files_to_load <- all_files[basename(all_files) %in% subset_data$MedicionArchivo]

# Load files into separate datasets named as the files
for (file in files_to_load) {
  # Extract file name without extension
  file_name <- gsub("\\..*$", "", basename(file))
  # Load file into a dataset with the same name as the file
  assign(file_name, read.csv(file,sep = " ", header = TRUE))
}


```

```{r}
files_to_load_sin_ext <- gsub("\\..*$", "", basename(files_to_load))
# Create list of datasets
datasets <- lapply(files_to_load_sin_ext, get)

# Add a new column with the dataset name to each dataset
for (i in seq_along(datasets)) {
  datasets[[i]]$dataset_name <- files_to_load_sin_ext[i]
  
  # Get value of nro_cartucho in same row as dataset_names in subset_data
  specified_value <- files_to_load_sin_ext[i]
  
  nro_cartucho <- subset_data$`Nro Cartucho`[subset_data$Medicion == specified_value]
  datasets[[i]]$nro_cartucho <- nro_cartucho
  
  tipo_muestra <- subset_data$Muestra[subset_data$Medicion == specified_value]
  datasets[[i]]$tipo_muestra <- tipo_muestra
  
  Prueba <- subset_data$Prueba[subset_data$Medicion == specified_value]
  datasets[[i]]$Prueba <- Prueba
  
  
  
  #Para agregar el valor de otra variable de esa medicion usar el siguiente template:
  #Mas abajo hay que hacer "as.character" de cada variable que se usa como color
  
  #variable1 <- subset_data$`columna con esa variable`[subset_data$Medicion == specified_value]
  #datasets[[i]]$nombre_de_variable <- variable1
}

# Merge all datasets into one
merged_dataset <- do.call(rbind, datasets)

merged_dataset$acu.t = as.numeric(as.character(merged_dataset$acu.t))
merged_dataset$acu.t <- merged_dataset$acu.t/1000

merged_dataset$acu.A1 = as.numeric(as.character(merged_dataset$acu.A1))
merged_dataset$acu.Promedio = as.numeric(as.character(merged_dataset$acu.Promedio))

merged_dataset$nro_cartucho = as.character(merged_dataset$nro_cartucho)
  
library(ggplot2)

#tipo_muestra dataset_name Prueba

# Create plot using ggplot2
ggplot(merged_dataset, aes(x = acu.t, y = acu.A1, color = dataset_name)) +
  geom_point() +
  scale_color_discrete(guide = guide_legend(title = "Prueba"))+
  scale_x_continuous(limits = c(0, 1000)) +
  #scale_y_log10() +
  labs(x = "t", y = "A") +
  ggtitle("A vs. t") +
  theme_bw()

```