---
title: "Plot A10"
---
Analisis del A10 intra-prueba (intra-día)
```{r}
library(usethis)
library(ggplot2)
library(dplyr)
library(credentials)

# Para no tener que volver a tipear user/pwd en git: In the shell, enter 
# git config --global credential.helper 'cache --timeout=10000000' 
# to store your password # for # ten million seconds (that’s roughly 16 weeks).



# Plot A10 vs prueba, color según muestra, forma según activación
ggplot(subset_data, aes(x = Prueba, y =`A10 (600s+CT) [Pa]`, color = Muestra, shape = Activacion)) +
  geom_point(size = 3) +
  geom_point() +
  #scale_x_continuous(limits = c(0, 2000)) +
  #scale_y_continuous(limits = c(0, 1000)) +
  labs(x = "Pruebas", y = "A10") +
  ggtitle("A10 vs. Mediciones, coloreado por muestra") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))

#------- analisis del A10 intra-prueba (intra-día)---------

# calculate CV values for each group
cv_data <- subset_data %>%
  group_by(Prueba) %>%
  summarise(cv = round(100*sd(`A10 (600s+CT) [Pa]`)/mean(`A10 (600s+CT) [Pa]`), 0))

#para calcular el N de cada grupo/prueba
N_data <- subset_data %>%
  count(Prueba, name = "N")

# plot boxplot with CV and N labels
ggplot(subset_data, aes(x = Prueba, y = `A10 (600s+CT) [Pa]`, color = Muestra)) +
  geom_boxplot() +
  labs(x = "Prueba", y = "A10") +
  ggtitle("A10 boxplot vs pruebas (con N y CV%)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  geom_text(data = N_data, aes(x = Prueba, y = min(subset_data$`A10 (600s+CT) [Pa]`), label = paste0("", N)), vjust = -1, size = 3, color = "red") +
  geom_text(data = cv_data, aes(x = Prueba, y = min(subset_data$`A10 (600s+CT) [Pa]`), label = paste0("", cv, "%")), vjust = 1, angle =55, size = 3, color = "blue", nudge_x = -0.2)

# tabla con CV y N por prueba (intra-día)
CV_N_intra_día <- merge(cv_data, N_data, "Prueba")
```

Variación inter-día para cada muestra
```{r}
#Variación inter-día para cada muestra
# calculate CV values for each group
cv_muestra <- subset_data %>%
  group_by(Muestra) %>%
  summarise(cv = round(100*sd(`A10 (600s+CT) [Pa]`)/mean(`A10 (600s+CT) [Pa]`), 0))

#para calcular el N de caja grupo/prueba
library(dplyr)

N_muestra <- subset_data %>%
  count(Muestra, name = "N")

#box plot con CV y N
ggplot(subset_data, aes(x = Muestra, y = `A10 (600s+CT) [Pa]`)) +
  geom_boxplot() +
  labs(x = "Muestra", y = "A10") +
  ggtitle("A10 boxplot vs Muestra (con N y CV%)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.7)) +
  geom_text(data = obs_muestra, aes(x = N_muestra$Muestra, y = max(subset_data$`A10 (600s+CT) [Pa]`), label = paste0("", obs)), vjust = 0, size = 3, color = "red") +
  geom_text(data = cv_muestra, aes(x = Muestra, y = max(subset_data$`A10 (600s+CT) [Pa]`), label = paste0("", cv, "%")), vjust = 0, angle =0, size = 3, color = "blue", nudge_x = 0.25)

# tabla con CV y N por muestra (inter-día)
CV_N_inter_día <- merge(cv_muestra, N_muestra, "Muestra")
```

Variación inter-día por muestra solo para INTEM
```{r}
#subset de mediciones de INTEM
intem <- subset_data[subset_data$Activacion == "INTEM", ]

# calculate CV values for each group
cv_muestra_in <- intem %>%
  group_by(Muestra) %>%
  summarise(cv = round(100*sd(`A10 (600s+CT) [Pa]`)/mean(`A10 (600s+CT) [Pa]`), 0))

#para calcular el N de caja grupo/prueba
library(dplyr)

N_muestra_in <- intem %>%
  count(Muestra, name = "N")

#box plot con CV y N
ggplot(intem, aes(x = Muestra, y = `A10 (600s+CT) [Pa]`)) +
  geom_boxplot() +
  labs(x = "Muestra", y = "A10") +
  ggtitle("A10 de INTEM vs Muestra (con N y CV%)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.7)) +
  geom_text(data = N_muestra_in, aes(x = Muestra, y = max(intem$`A10 (600s+CT) [Pa]`), label = paste0("", N)), vjust = 0, size = 3, color = "red") +
  geom_text(data = cv_muestra_in, aes(x = Muestra, y = max(intem$`A10 (600s+CT) [Pa]`), label = paste0("", cv, "%")), vjust = 0, angle =0, size = 3, color = "blue", nudge_x = 0.2)

# tabla con CV y N por muestra para INTEM (inter-día)
CV_N_inter_día_intem <- merge(cv_muestra_in, N_muestra_in, "Muestra")
```
Variación inter-día por muestra solo para EXTEM
```{r}
#subset de mediciones de EXTEM
extem <- subset_data[subset_data$Activacion == "EXTEM", ]

# calculate CV values for each group
cv_muestra_ex <- extem %>%
  group_by(Muestra) %>%
  summarise(cv = round(100*sd(`A10 (600s+CT) [Pa]`)/mean(`A10 (600s+CT) [Pa]`), 0))

#para calcular el N de caja grupo/prueba
library(dplyr)

N_muestra_ex <- intem %>%
  count(Muestra, name = "N")

#box plot con CV y N
ggplot(extem, aes(x = Muestra, y = `A10 (600s+CT) [Pa]`)) +
  geom_boxplot() +
  labs(x = "Muestra", y = "A10") +
  ggtitle("A10 de EXTEM vs Muestra (con N y CV%)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.7)) +
  geom_text(data = N_muestra_ex, aes(x = Muestra, y = max(extem$`A10 (600s+CT) [Pa]`), label = paste0("", N)), vjust = 0, size = 3, color = "red") +
  geom_text(data = cv_muestra_ex, aes(x = Muestra, y = max(extem$`A10 (600s+CT) [Pa]`), label = paste0("", cv, "%")), vjust = 0, angle =0, size = 3, color = "blue", nudge_x = 0.2)

# tabla con CV y N por muestra para EXTEM (inter-día)
CV_N_inter_día_extem <- merge(cv_muestra_ex, N_muestra_ex, "Muestra")
```


CARTUCHOS: Plot A10 vs prueba, color nombre de cartucho
```{r}
#Plot A10 vs prueba, color nombre de cartucho

#eliminamos mediciones sin datos de cartuchos
# ??????

#plot
subset_data$Nro_Cartucho_Factor <- factor(subset_data$`Nro Cartucho`, levels = unique(subset_data$`Nro Cartucho`))

ggplot(subset_data, aes(x = Prueba, y =`A10 (600s+CT) [Pa]`, color = Nro_Cartucho_Factor)) + 
  labs(x = "Prueba", y = "A10") +
  geom_point(size = 2) +
  ggtitle("A10 vs. Pruebas coloreado según el cartucho") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
```

subsets según la muestra para analizar los CV del A10 inter-prueba
```{r}
#subseteamos según la muestra para analizar los CV del A10 inter-prueba
rotrol <- subset_data[subset_data$Muestra == "ROTROL N", ]
rotrol_25 <- subset_data[subset_data$Muestra == "ROTROL_N_25", ]
sangre <- subset_data[subset_data$Muestra == "SANGRE", ]
plasma <- subset_data[subset_data$Muestra == "PLASMA SIEMENS", ]
plasma_25 <- subset_data[subset_data$Muestra == "PLASMA_SIEMENS_25", ]
plasma_in <- plasma[plasma$Activacion == "INTEM", ]
plasma_ex <- plasma[plasma$Activacion == "EXTEM", ]
rotrol_in <- rotrol[rotrol$Activacion == "INTEM", ]
rotrol_ex <- rotrol[rotrol$Activacion == "EXTEM", ]
sangre_in <- sangre[sangre$Activacion == "INTEM", ]
sangre_ex <- sangre[sangre$Activacion == "EXTEM", ]

#subseteamos según la activación
intem <- subset_data[subset_data$Activacion == "INTEM", ]
extem <- subset_data[subset_data$Activacion == "EXTEM", ]
```
```{r}
table(intem$Muestra)
table(extem$Muestra)
```

```{r}



```

Demases...
```{r}
# Convert date range to proper format
#start_date <- as.Date("2022-11-30")
#end_date <- as.Date("2023-04-05")



# Append ".dat" to file_name column
#subset_data$MedicionArchivo <- paste(subset_data$Medicion, ".dat", sep = "")

```




```

